name: Deploy to Cloud Run

on:
  push:
    branches: [ main, dev ]
  # Pull request trigger is important for:
  # 1. Testing deployments before merging to main
  # 2. Validating builds in isolation
  # 3. Catching issues early in the CI pipeline
  # 4. Allowing reviewers to test changes
  pull_request:
    branches: [ main, dev ]

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  SERVICE_NAME: anthropic-clone
  REGION: us-central1
  REPOSITORY: us-central1-docker.pkg.dev

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker $REPOSITORY

    - name: Check Artifact Registry repository
      id: check_repo
      continue-on-error: true
      run: |
        if gcloud artifacts repositories describe $SERVICE_NAME --location=$REGION; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Artifact Registry repository
      if: steps.check_repo.outputs.exists == 'false'
      run: |
        echo "Repository does not exist. Please create it manually with the following command:"
        echo "gcloud artifacts repositories create $SERVICE_NAME --repository-format=docker --location=$REGION"
        exit 1

    - name: Build
      run: |-
        docker build \
          --tag "$REPOSITORY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA" \
          --tag "$REPOSITORY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:latest" \
          .

    - name: Push
      run: |-
        docker push "$REPOSITORY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA"
        docker push "$REPOSITORY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:latest"

    - name: Deploy
      run: |-
        gcloud run deploy $SERVICE_NAME \
          --image "$REPOSITORY/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA" \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }},BIGTABLE_INSTANCE_ID=${{ secrets.BIGTABLE_INSTANCE_ID }}" 